countries:
  ar: "Argentina"
  at: "Austria"
  au: "Australia"
  be: "Belgium"
  br: "Brazil"
  ca: "Canada"
  ch: "Switzerland"
  cl: "Chile"
  co: "Colombia"
  cz: "Czech Republic"
  de: "Germany"
  dk: "Denmark"
  ee: "Estonia"
  es: "Spain"
  fi: "Finland"
  fr: "France"
  gb: "United Kingdom"
  gr: "Greece"
  hr: "Croatia"
  hu: "Hungary"
  ie: "Ireland"
  is: "Iceland"
  it: "Italy"
  jp: "Japan"
  kr: "South Korea"
  lt: "Lithuania"
  lu: "Luxembourg"
  lv: "Latvia"
  mx: "Mexico"
  nl: "Netherlands"
  no: "Norway"
  nz: "New Zealand"
  pl: "Poland"
  pt: "Portugal"
  ro: "Romania"
  rs: "Serbia"
  ru: "Russia"
  se: "Sweden"
  sg: "Singapore"
  si: "Slovenia"
  sk: "Slovakia"
  th: "Thailand"
  us: "United States"
  za: "South Africa"
